---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[composer::default]
    attributes: {
      "composer": {
        "install_globally": true
      }
    }
